name: Publish Docker image

on:
  release:
    types: [published] # Trigger the workflow when a new release is published
  workflow_dispatch: # Allow manual triggering of the workflow

env:
  REGISTRY: docker.io
  IMAGE_NAME: justinferrara968/justtransfer-frontend

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Create .env file
        run: |
          echo "VITE_API_URL=${{ vars.VITE_API_URL }}" >> .env
          echo "VITE_FRONTEND_URL=${{ vars.VITE_FRONTEND_URL }}" >> .env
          echo "VITE_EMAIL_INFO=${{ vars.VITE_EMAIL_INFO }}" >> .env
          echo "VITE_UMAMI_URL=${{ vars.VITE_UMAMI_URL }}" >> .env
          echo "VITE_UMAMI_WEBSITE_ID=${{ vars.VITE_UMAMI_WEBSITE_ID }}" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
